### ISSUE TITLE
build failed after adding background.ts. builder updated and target to es5 

### ISSUE THREAD

**Issue by shirlikc** [just-jeb/angular-chrome-extension#4]
run ng build:
C:\Users\Shirli\Development\angular-chrome-extension>ng build

chunk {background} background.js, background.js.map (background) 1.05 kB [initia
l] [rendered]
chunk {main} main.js, main.js.map (main) 60.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 165 kB [initial] [r
endered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 604
 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 10.1 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.52 MB [initial] [rendered]
Date: 2020-03-10T21:20:38.131Z - Hash: 1b742c9882941a697bed - Time: 10413ms

ERROR in ./src/background.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Shirli\Development\angular-chrome-extension\src\background.ts is
 missing from the TypeScript compilation. Please make sure it is in your tsconfi
g via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Shirli\Development\angula
r-chrome-extension\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:
933:23)
    at C:\Users\Shirli\Development\angular-chrome-extension\node_modules\@ngtool
s\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by shirlikc** [comment]
after updating tsconfig with :
   "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ] the build passed

**Comment by just-jeb** [comment]
Are you talking about this repo? Building just fine for me...

**Comment by GuillaumeBonnet** [comment]
Thank you for this ticket I got stuck on the same problem for too long.

This repo is in angular 8.
In angular 9 there is a  changement in tsconfig.app.json:
```
"include": [
-    "src/**/*.ts" // => includes background.ts
+    "src/**/*.d.ts" // => doesn't include background.ts
]

```
I added  "src/background.ts" to the "files" array property

 ```
 "files": [
    "src/main.ts",
    "src/polyfills.ts",
+    "src/background.ts"
  ],
```

And thank you for this medium article!

**Comment by just-jeb** [comment]
@GuillaumeBonnet Thanks for the research! I guess I need to update the repo.

**Comment by GuillaumeBonnet** [comment]
@just-jeb my pleasure,
If you update it you will also see that:
- aot is already true by default
- background.ts is transpiled into "background-es2015.js" and "background-es5.js"
  so I adapted the manifest accordingly:

```
"scripts": [
          "background-es2015.js",
          "runtime-es2015.js"
      ]
```
cheers

**Comment by VahidNaderi** [comment]
> Thank you for this ticket I got stuck on the same problem for too long.
> 
> This repo is in angular 8.
> In angular 9 there is a changement in tsconfig.app.json:
> 
> ```
> "include": [
> -    "src/**/*.ts" // => includes background.ts
> +    "src/**/*.d.ts" // => doesn't include background.ts
> ]
> ```
> 
> I added "src/background.ts" to the "files" array property
> 
> ```
> "files": [
>    "src/main.ts",
>    "src/polyfills.ts",
> +    "src/background.ts"
>  ],
> ```
> 
> And thank you for this medium article!

Don't forget to add chrome to types

```
...
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["chrome"]
  }
...
```

**Comment by just-jeb** [comment]
Thanks @VahidNaderi, I should really update this repo to the latest version.
